### ISSUE TITLE
Few suggestions/requests

### ISSUE THREAD

**Issue by hasnat** [mulbc/vaultPass#15]
Great extension, I have it working nicely.

Few things I would like to point out.
- In docs with info specifying where to add credentials. Provide curl or vault agent commands. As paths in vault for starters get a bit confusing. May be also add some screenshots from vault ui.
- Allow path other than `vaultPass` configureable via options.
- Keep default lookup or matching secrets but add custom search on list page to override it.
- If no username or password keys in secret instead of undefined warn user to add appropriate key, value and disable copying of username and/or password
- Option to add more than one vault servers

**Comment by Ogy** [comment]
i would love to have disabled copying username+password
but than i've realized you can use inspect element / developer tools to show filled username/password

**Comment by mulbc** [comment]
Glad you found some use for my Extension! Also good feedback - I know that the docs can be a bit hard to understand, but I was hoping for people to ask questions, so I know where to improve them.
@hasnat since it looks like you figured everything out - could you maybe improve the docs and send me a PR?

Also:

- Why do you think the `vaultPass` path should be configurable?
- What do you mean with a "custom search" exactly? What I had in mind as a future feature was to do a recursive search deep into folders (if there are any)... but basically with the same algorithm.
- You want me to warn users every time they list potential secrets that there's a key in their Vault which does not include all the necessary fields?
- I'm not planning (as of now) to support using more than one Vault server in parallel (but happy for PRs that would enable that ;) )

**Comment by hasnat** [comment]
sure, I'd be happy to send PR for documentation updates.

- As someone might already have credentials in some other path, they will have to copy it just for sake of vaultPass. Adding a configurable path would allow users to test with any path they want.
- vaultPass is searching based on hostname in url, that should remain default but if user wants to search for anything else in vaultPass they don't necessarily need to visit that host to see it visible in selection. E.g there would be username/passowrd entry called `LDAP` in my vaultPass path and I know which hosts I visit would accept LDAP credentials.
- On list of secrets if they don't have any username or password kv vaultPass just adds `undefined` in clipboard or input fields. vaultPass should instead add some warning icon or message stating this path is missing username/password kv.
- great to see multiple vault servers could be accepted by a PR.

We would need help of vue, reactjs or similar suggestions might bring a lot of view code.

**Comment by afteroot** [comment]
Also want to add. 
it will be perfect in future to add autofill variables to page
and as for 
```
I'm not planning (as of now) to support using more than one Vault server in parallel (but happy for PRs that would enable that ;) )
```
I think that it will be unusible. (keepalived + haproxy)

**Comment by mulbc** [comment]
I just added a search field with dfd5d25 and will most likely release 2.4 very soon to include that. I'll also try to release these new features for Firefox as well

**Comment by mulbc** [comment]
Closing this, since most suggestions have been implemented by now
