### ISSUE TITLE
GUI doesn't open anymore

### ISSUE THREAD

**Issue by snake3lake** [mulbc/vaultPass#26]
GUI doesn't open anymore on Ubuntu 21.10. It does on Ubuntu 20.04.
After installing it does, but not after restarting FF.

Ubuntu 21.10
Firefox: 95.0.2

**Comment by mulbc** [comment]
Thanks for reporting the Bug and Happy New Years!

I just tried to reproduce this on Fedora 35 with Mozilla Firefox 95.0.2 and couldn't. The UI opens up perfectly for me.

Would you be able to create a little video for me where you show this bug?

**Comment by snake3lake** [comment]
Happy New Years!
Here's the video.

**Comment by snake3lake** [comment]
Happy New Years!
Here's the video.

[firefox-vaultpass.webm.gz](https://github.com/mulbc/vaultPass/files/7813879/firefox-vaultpass.webm.gz)

**Comment by mulbc** [comment]
The video helped a lot - and I can see the same behavior on my side... Though when I go to debug the Addon in Firefox, it starts to work as soon as I inspect it :/
`about:devtools-toolbox?id=addon%40blum.coffee&type=extension`
When I close the inspector, the bug returns

Interestingly, it behaves the same way, no matter if you are logged in or not :/

**Comment by mulbc** [comment]
I have just submitted version 2.3 for Firefox which should help in this. I have made some other changes in that version  already, which I only published to the Chrome store, since I also moved to Manifest version 3, but backported to version 2 now to have this bug fixed :)
Once 2.3 is out, please try again and excuse the meantime

**Comment by snake3lake** [comment]
It's working again!
