### ISSUE TITLE
html code in Vault secrets are executed

### ISSUE THREAD

**Issue by mulbc** [mulbc/vaultPass#3]
When secrets in Vault contain HTML code - this is executed when displaying that information in the popup.
This could be a security issue

**Comment by ThibaultJanBeyer** [comment]
That is easily fixed if you use [.textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) instead of `innerHTML`. The former will not execute code but place it as text. Otherwise you would have to [escape](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.231_-_HTML_Escape_Before_Inserting_Untrusted_Data_into_HTML_Element_Content) or sanatize the input  before placing it.
