### ISSUE TITLE
How can I store different credentials for the same URL?

### ISSUE THREAD

**Issue by tamere-allo-peter** [mulbc/vaultPass#33]
In the *Current features* list on this project's frontpage *(README.md)* there's this on the second line : **Get list of potential credentials in Popup**

Does this mean it is possible to store several different usernames/passwords for the very same site and the very same users, or is it impossible to do so ?

Sorry to ask but this is not very clear to me.

We currently use vaultPass *v2.3.2* with HashiCorp Vault *v1.10.0* with LDAP login and it works perfectly for most of the websites we are using, until we encounter a website for which we have several different access levels, with different usernames, e.g. *admin* and *user*, each having his own password.

Then we don't know how to put them into HashiCorp Vault in a way that would make vaultPass propose a list of available credentials for that particular website, allowing our users to choose between *admin* and his password or *user* and his password.

Is this possible ? If so, please could you explain how to do ?

Thanks so much in advance.

**Comment by mulbc** [comment]
hey there, thanks for using my software!

Credentials are stored in the kv mount in this path:
`/vaultPass/[someOrg]/url`

We use "someOrg" to group credentials by teams (even if that team is just a single person for example)
url is basically a regex that will match to the URL.
You probably already know this since you use the extention ;)

While it is *not* possible to use the exact same _path_ (e.g. have two credentials at /vaultPass/it/yahoo.com) for two different credentials, I think for your use case (different levels of access) it would make more sense to separate these out into different orgs.
That way you could put your admin credentials into /vaultPass/it-secure/yahoo.com and your user credentials into /vaultPass/it/yahoo.com. This has the additional benefit that you can share the user credentials with other teams without giving them admin permissions in the very same step.

If this is too cumbersome, I would recommend tinkering around with the regex. That way you could have one entry as
/vaultPass/it/yahoo.com
and another one as 
/vaultPass/it/*yahoo.com
which should map to pretty much the same website, but you can put different credentials into them.

If this solves your issue, please close this

**Comment by mulbc** [comment]
Closing since there was no response

**Comment by tamere-allo-peter** [comment]
@mulbc yes the first suggestion is what I thought about doing, but clearly it's more cumbersome as we may not currently have additional orgs, and another team is in charge of managing the LDAP server (AD).

The second suggestion is what I'll try ASAP and I'll let you know how it goes. Thanks again for your help.

**Comment by mulbc** [comment]
The orgs that I mentioned wouldn't exist within LDAP. Orgs in the VaultPass case are just folders that are mapped to LDAP groups via [Vault Policies](https://developer.hashicorp.com/vault/docs/concepts/policies)

Thus you can just create different orgs like  /secret/vaultPass/org1 /secret/vaultPass/org2 and make them both accessible to the very same LDAP group, but store different credentials into these 'folders'

**Comment by tamere-allo-peter** [comment]
Ahhhhhh, ok. I misunderstood then. As I mapped AD group name to Vault org, I didn't understood they could be named differently. I'll let you know if the second solution works, but at least the first one should. Thanks again.

**Comment by tamere-allo-peter** [comment]
@mulbc unfortunately second solution doesn't seem to work, as you can see in the attached pictures :

![rh1](https://user-images.githubusercontent.com/85658105/211925197-18491272-6633-446a-8635-ad6134769a58.png)

![rh2](https://user-images.githubusercontent.com/85658105/211925246-aa11ba56-81ed-4993-b36d-bdcdcf0db111.png)

You can close this, we'll use the first solution then.

Thanks again. Have a nice day.
